spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://neiyycoin2017.mysql.rds.aliyuncs.com:3306/uportal?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: yycoinadmin
    password: Yycoinoa2017
    druid:
      max-active: 200
      initial-size: 20
      max-wait: 60000
      min-idle: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      pool-prepared-statements: true
      max-open-prepared-statements: 200
#以下为监控统计
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-enable: true
        session-stat-max-count: 500
        profile-enable: true
        exclusions: /*.js,/*.gif,/*.jpg,/*.bmp,/*.png,/*.css,/*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
apache:
  rocketmq:
    #消费者的配置
    consumer:
      namesrvAddr: 127.0.0.1:9876
      groupName: MayCurConsumerGroup
      topicName: MayCurTopic
      consumeThreadMin: 20
      consumeThreadMax: 64
      consumeMessageBatchMaxSize: 1
    #生产者的配置
    producer:
      groupName: MayCurProducerGroup
      namesrvAddr: 127.0.0.1:9876
      #消息最大长度 默认1024*4(4M)
      maxMessageSize: 4096
      sendMsgTimeout: 3000
      #发送消息失败重试次数，默认2
      retryTimesWhenSendFailed: 2
      topicName: MayCurTopicmybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/ext/*.xml
server:
  servlet:
    jsp:
      init-parameters:
                development: true
    session:      timeout: 1800
  port: 9080
logging:  config: classpath:logback-spring.xml